/**
 * Generates a Surge *panel* script that shows each subscription's traffic
 * usage (used / total / expiry) in the Surge dashboard.
 *
 * Why generate instead of ship a static script: the subscription URLs are
 * private, so they must never live in the (public) repo. The tool bakes the
 * configured URLs into a script written to the user's local `outputDir`.
 *
 * How it works at runtime: some panels (e.g. xboard) only return the
 * `subscription-userinfo` header to a Clash/v2ray UA, not to Surge's UA, so the
 * script re-fetches each subscription with a Clash UA and reads that header.
 * Each airport is labelled by its `content-disposition` filename when present.
 */
export const buildAirportTrafficScript = (subscriptionUrls: string[]): string => {
  const subsLiteral = subscriptionUrls.map((url) => `  { url: ${JSON.stringify(url)} },`).join('\n');

  return `/* AUTO-GENERATED by surge-vless-bridge. Do not edit by hand; re-run \`sync\`. */
/* Surge panel script: airport subscription traffic usage. */

const SUBS = [
${subsLiteral}
];

const CLASH_UA = 'clash-verge/v1.7.0';
const GB = 1024 * 1024 * 1024;

const fmtGB = (bytes) => (bytes / GB).toFixed(2) + ' GB';

const fmtDate = (epochSeconds) => {
  if (!epochSeconds) return '永久';
  const d = new Date(epochSeconds * 1000);
  const p = (n) => String(n).padStart(2, '0');
  return d.getFullYear() + '-' + p(d.getMonth() + 1) + '-' + p(d.getDate());
};

const headerValue = (headers, name) => {
  if (!headers) return '';
  for (const key in headers) {
    if (key.toLowerCase() === name) return headers[key];
  }
  return '';
};

const airportName = (headers, fallback) => {
  const cd = headerValue(headers, 'content-disposition');
  const m = /filename\\*?=(?:UTF-8'')?["']?([^"';]+)/i.exec(cd);
  if (m) {
    try {
      return decodeURIComponent(m[1]).replace(/\\.(conf|ya?ml|txt)$/i, '');
    } catch (e) {
      return m[1].replace(/\\.(conf|ya?ml|txt)$/i, '');
    }
  }
  return fallback;
};

const parseUserInfo = (raw) => {
  const kv = {};
  raw.split(';').forEach((part) => {
    const pair = part.trim().split('=');
    if (pair[0]) kv[pair[0].trim()] = Number(pair[1]);
  });
  const used = (kv.upload || 0) + (kv.download || 0);
  const total = kv.total || 0;
  return {
    used,
    total,
    remain: Math.max(total - used, 0),
    pct: total ? (used / total) * 100 : 0,
    expire: kv.expire || 0,
  };
};

const results = new Array(SUBS.length).fill(null);
let pending = SUBS.length;

const finish = () => {
  const lines = results.map((r, i) => {
    if (!r) return 'sub' + (i + 1) + ': 获取失败';
    if (r.error) return (r.name || 'sub' + (i + 1)) + ': ' + r.error;
    return r.name + '  剩 ' + fmtGB(r.remain) + ' / ' + fmtGB(r.total) +
      '  (已用 ' + r.pct.toFixed(1) + '%)  到期 ' + fmtDate(r.expire);
  });

  const first = results.find((r) => r && !r.error);
  const title = first
    ? '机场流量  剩余 ' + (100 - first.pct).toFixed(1) + '%'
    : '机场流量';

  $done({
    title: title,
    content: lines.join('\\n'),
    icon: 'airplane.circle.fill',
    'icon-color': '#2979FF',
  });
};

SUBS.forEach((sub, index) => {
  const host = (sub.url.split('/')[2] || 'sub');
  $httpClient.get({ url: sub.url, headers: { 'User-Agent': CLASH_UA } }, (err, resp) => {
    if (err) {
      results[index] = { name: host, error: '请求错误' };
    } else {
      const headers = resp && resp.headers;
      const info = headerValue(headers, 'subscription-userinfo');
      if (info) {
        const parsed = parseUserInfo(info);
        parsed.name = airportName(headers, host);
        results[index] = parsed;
      } else {
        results[index] = { name: airportName(headers, host), error: '无流量头' };
      }
    }
    pending -= 1;
    if (pending === 0) finish();
  });
});
`;
};

/** The [Panel] / [Script] lines the user adds to their Surge profile. */
export const airportTrafficSurgeSnippet = (scriptPath: string): string =>
  [
    '[Panel]',
    'AirportTraffic = script-name=AirportTraffic, update-interval=3600',
    '',
    '[Script]',
    `AirportTraffic = type=generic, script-path=${scriptPath}`,
  ].join('\n');
